import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Toaster } from 'sonner';

import { fetchUserFromSession } from '@/actions/authActions';
import { UserProvider } from '@/providers/userProvider/UserProvider';
import { QueryProvider } from '@/providers/queryProvider';
import { OverlayProvider } from '@/providers/overlayProvider/OverlayProvider';
import { LoadingOverlay } from '@/components/LoadingOverlay';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserFromSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <OverlayProvider>
            <UserProvider initialUser={user}>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                {children}
                <LoadingOverlay />
                <Toaster />
              </ThemeProvider>
            </UserProvider>
          </OverlayProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
