services:
  backend:
    build: ./backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-8001}
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_LISTEN_PORT:-8001}:${PGADMIN_LISTEN_PORT:-8001}"
    depends_on:
      - postgres

volumes:
  db_data:
  pgadmin:
