import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="relative m-auto flex max-w-xxl justify-center overflow-hidden pt-[75px] 4xl:overflow-visible">
        {children}
      </main>
    </>
  );
}
