import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import type { Metadata } from 'next';
import { AppSidebar } from '@/components/AppSidebar';
import { cookies } from 'next/headers';
import { OrganizationProvider } from '@/providers/organizationProvider';
import { getOrganization } from '@/actions/organizationActions';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string; orgId: number }>;
}>) {
  const { orgId } = await params;

  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';
  const organization = await getOrganization(orgId);

  return (
    <OrganizationProvider initialOrganization={organization}>
      <SidebarProvider defaultOpen={defaultOpen}>
        <AppSidebar organization={organization} />
        <main className="w-full">
          <div className="h-[75px] w-full">
            <SidebarTrigger />
          </div>
          {children}
        </main>
      </SidebarProvider>
    </OrganizationProvider>
  );
}
