import type { Metadata } from 'next';

import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="relative m-auto flex max-w-xxl justify-center overflow-hidden pt-[75px] 4xl:overflow-visible">
        {children}
      </main>
      <Footer />
    </>
  );
}
